quarkus.application.name=weather-forecast-frauenfeld-llm
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n

weather.api.latitude=${WEATHER_API_LATITUDE}
weather.api.longitude=${WEATHER_API_LONGITUDE}

quarkus.rest-client.weather-api.url=${QUARKUS_REST_CLIENT_WEATHER_API_URL}
weather.fetch.interval=${WEATHER_FETCH_INTERVAL:12h}

quarkus.langchain4j.openai.base-url=https://models.inference.ai.azure.com
quarkus.langchain4j.openai.chat-model.model-name=${QUARKUS_LANGCHAIN4J_OPENAI_CHAT_MODEL_MODEL_NAME}
quarkus.langchain4j.openai.chat-model.max-tokens=${QUARKUS_LANGCHAIN4J_OPENAI_CHAT_MODEL_MAX_TOKENS}
quarkus.langchain4j.openai.api-key=${QUARKUS_LANGCHAIN4J_OPENAI_API_KEY:none}
quarkus.langchain4j.openai.timeout=60s

quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=${DB_URL}
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true
quarkus.flyway.locations=db/migration
quarkus.hibernate-orm.log.sql=false

%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
%test.quarkus.datasource.username=sa
%test.quarkus.datasource.password=
%test.quarkus.flyway.migrate-at-start=true